version: "3.4"

services:
    db:
        image: "postgres:latest"
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=nossoportifolio
        ports:
          - '5432:5432'